### ISSUE TITLE
Missing commands & Rate Limited

### ISSUE THREAD

**Issue by Sorok-Dva** [Green0-0/Discord-LLM-v2#1]
Hello,

Thanks for this project, I would like to try it but got some issues.
Actually there is a lot of missing commands, all related to characters.

I only have these commands : 

![image](https://github.com/user-attachments/assets/c50b3529-3160-44a8-8391-24efbea41f48)
![image](https://github.com/user-attachments/assets/f09bfd2a-d9ee-4d30-909b-39d3bbc3171e)

I did add myself as an admin

Thanks for your help

**Comment by Sorok-Dva** [comment]
Also just got a "We are being rate limited. PUT https://discord.com/api/v10/applications/517322105105154048/commands responded with 429" error

**Comment by Green0-0** [comment]
Do /reload to add the commands, then reload your discord tab, I do a lot of live updates on the bot so the reload is there so I can sync changes.
The rate limit is a discord thing, I can't fix that, you just have to wait.

**Comment by Sorok-Dva** [comment]
> Do /reload to add the commands, then reload your discord tab, I do a lot of live updates on the bot so the reload is there so I can sync changes. The rate limit is a discord thing, I can't fix that, you just have to wait.

Thanks for your quick reply ! I just tested it again on another computer and I do have the commands, I guess the main problem was linked to my first computer.

And yeah I know rate limit is from discord but the fact is I got this error without being abled to use it, so how can I be rated limited if I didn't used the bot ?

**Comment by Green0-0** [comment]
Strange. What command did you run to get ratelimited?

**Comment by Sorok-Dva** [comment]
I don't remember but it was about basics command like /help or /reload
But it's ok now I did manage to run the commands successfully but I'm facing new issues : 

```
<Log> Generated new webhook for character "Aidenus" in channel "lisa"
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "Ah" is not found
!!! ERROR !!!
Traceback (most recent call last):
  File "/srv/node/Discord-LLM-v2/libs/config.py", line 71, in queue
    if response[0] == response[-1] and response[0] == "\"":
IndexError: string index out of range

-------------
!!! ERROR !!!
Traceback (most recent call last):
  File "/srv/node/Discord-LLM-v2/libs/config.py", line 71, in queue
    if response[0] == response[-1] and response[0] == "\"":
IndexError: string index out of range

-------------
!!! ERROR !!!
Traceback (most recent call last):
  File "/srv/node/Discord-LLM-v2/libs/config.py", line 71, in queue
    if response[0] == response[-1] and response[0] == "\"":
IndexError: string index out of range

-------------
Failed to generate response because of error:
'string index out of range'
```

While trying to get an answer. Also how did the trigger of characters works exactly ? I don't manage to understand it and how can they speaks between them

**Comment by Green0-0** [comment]
Weird, I've never gotten that error before. Did you mess with any of the configs/prompt formats/model/etc? Have you gotten the bot to respond at all?

For character selection:
I use an LLM for classification, determining the next speaker based on the chat history and a list of toggled characters. Its honestly not very effective, requires a lot of prompt tuning each time the LLM used changes.

**Comment by Green0-0** [comment]
The reason you would get that error is because the API returned the input and did not respond with a text completion

**Comment by Green0-0** [comment]
Actually, the defaults might be outdated, let me see if I need to update them.

**Comment by Green0-0** [comment]
I tested it just now and the defaults should work

**Comment by Sorok-Dva** [comment]
Thank you for your answer. The error seems to be gone. However, I still don't understand how to start making them talk. When I ping the bot or say the name of a character, nothing happens, I have to use the /reply_as command to get a semblance of a response.
The /toggle_character command was used on both characters.

Concretely, how do I get them to start talking without my intervention ?

<img width="896" alt="image" src="https://github.com/user-attachments/assets/57c17e14-3ddd-460e-bbf9-938b476e9710">

**Comment by Green0-0** [comment]
Can you enable /deep_logging? You should get a message and a completion each time you send something for the queue model, check what it is saying.

**Comment by Sorok-Dva** [comment]
I've enabled /deep_logging but when I speak in the channel, trying to ping the bot or the character nothings happpens and no log

**Comment by Green0-0** [comment]
Pinging the bot doesn't do anything, but you should get a log upon sending any message as long as deep_logging is enabled. The only time you won't get logs is if there is somehow no characters enabled in a channel with /toggle_character (which is channel specific, by the way)

**Comment by Sorok-Dva** [comment]
I don't have any logs when I'm writing something, also I did enabled the characters with toogle_character command in a specific channel. And when speaking in this specific channel nothings happens.

**Comment by Green0-0** [comment]
I can't seem to reproduce the issue; I started the bot, deleted all the characters and created a new one and it properly queues. Did you modify the code in any way?

**Comment by Sorok-Dva** [comment]
> Did you modify the code in any way?

Yes I've edited the admin ID to my user id : 

```
+++ b/data.py
@@ -29,7 +29,7 @@ def init(Log_stream : StringIO):
     # Stores a list of admins who have permission to manage the bot
     # Adds me as an admin
     global admins
-    admins = ["320920450714828800"]
+    admins = ["141895511643914240"]
```

And i've also hard-coded my characters instead of basics characters 

But that's the only modifications I did

**Comment by Green0-0** [comment]
I've reuploaded the files (though nothing has changed); can you try just downloading the code and running it without any modifications, besides adding yourself as admin? Just call /reload, /purge_webhooks, /deep_logging, /toggle_character <any of the default ones> and then send one message saying anything, and wait for a log, then send a messsage saying a characters name

Also make sure your bot has both the necessary privileged intents on the dev portal and in your server
